### PR TITLE
Fix a few parser style issues.

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
The issue is that lexer_hex_to_character is used by some internal tests. I don't really like this, but we can keep it if needed.

**Comment by zherczeg** [comment]
Any suggestion?

**Comment by LaszloLango** [comment]
Let's keep it or declare as an extern function in the related unit test file.

**Comment by akosthekiss** [comment]
My two cents: keep `lexer_hex_to_character` as non-static. There are quite some other non-API functions that are accessed from unit tests, too. (Even in test-lit-char-helpers.c, e.g., `lit_char_get_utf8_length`.) For now, we have to live with keeping them non-static, IMHO.

Some (distant?) future work may deal with solving this, i.e., how to make those functions static that are only published for testing reasons. But that will deal with all such functions then, not only this one.

**Pull request merged**
