### PR TITLE
Move push literal number opcodes to basic opcodes

### PR DESCRIPTION
**Pull request by rerobika**
`obj[number]` is a widely used structure especially for array element indexing, however super property assignment is not.
This patch moves super-assignment opcodes to ext opcodes and fills the freed 3 basic opcodes with push-literal-number ones.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik robert.fancsik@h-lab.eu

### CODE REVIEW

**Comment by rerobika** [comment]
Benchmark | Heap (bytes) | Stack (bytes) | Perf (sec) |
----: | ----: | ----: | ----: | 
3d-cube.js | 10992 -> 11200 : -1.892% | 13800 -> 13612 : **+1.362%** | 1.088 -> 1.094 : -0.526% | 
3d-morph.js | 289232 -> 289232 : 0.000% | 1576 -> 1576 : 0.000% | 1.308 -> 1.327 : -1.486% | 
3d-raytrace.js | 117656 -> 110872 : **+5.766%** | 2540 -> 2540 : 0.000% | 1.272 -> 1.281 : -0.644% | 
access-binary-trees.js | 27120 -> 28656 : -5.664% | 3432 -> 3432 : 0.000% | 0.752 -> 0.751 : +0.129% | 
access-fannkuch.js | 1792 -> 1792 : 0.000% | 1648 -> 1648 : 0.000% | 2.534 -> 2.529 : +0.213% | 
access-nbody.js | 4600 -> 4600 : 0.000% | 1736 -> 1736 : 0.000% | 1.454 -> 1.455 : -0.077% | 
bitops-3bit-bits-in-byte.js | 1024 -> 1024 : 0.000% | 1592 -> 1592 : 0.000% | 0.711 -> 0.713 : -0.284% | 
bitops-bits-in-byte.js | 984 -> 984 : 0.000% | 1592 -> 1592 : 0.000% | 1.008 -> 1.009 : -0.052% | 
bitops-bitwise-and.js | 752 -> 752 : 0.000% | 1344 -> 1344 : 0.000% | 1.208 -> 1.213 : -0.415% | 
bitops-nsieve-bits.js | 61184 -> 61184 : 0.000% | 1592 -> 1592 : 0.000% | 1.474 -> 1.478 : -0.276% | 
controlflow-recursive.js | 1288 -> 1280 : +0.621% | 61584 -> 61584 : 0.000% | 0.520 -> 0.520 : +0.080% | 
crypto-aes.js | 28040 -> 28224 : -0.656% | 2288 -> 2288 : 0.000% | 0.871 -> 0.882 : -1.263% | 
crypto-md5.js | 70968 -> 70960 : +0.011% | 1704 -> 1704 : 0.000% | 0.722 -> 0.726 : -0.506% | 
crypto-sha1.js | 46328 -> 46320 : +0.017% | 1720 -> 1720 : 0.000% | 0.739 -> 0.740 : -0.053% | 
crypto.js | 51704 -> 51704 : 0.000% | 3156 -> 3156 : 0.000% | 8.507 -> 8.533 : -0.307% | 
date-format-tofte.js | 8952 -> 8944 : +0.089% | 1992 -> 1992 : 0.000% | 0.961 -> 0.960 : +0.149% | 
date-format-xparb.js | 15144 -> 15144 : 0.000% | 2552 -> 2552 : 0.000% | 0.689 -> 0.689 : +0.109% | 
deltablue.js | 455544 -> 456496 : -0.209% | 3540 -> 3540 : 0.000% | 5.304 -> 5.299 : +0.096% | 
math-cordic.js | 2048 -> 2048 : 0.000% | 1592 -> 1592 : 0.000% | 1.666 -> 1.664 : +0.159% | 
math-partial-sums.js | 1512 -> 1512 : 0.000% | 1568 -> 1568 : 0.000% | 1.152 -> 1.138 : **+1.277%** | 
math-spectral-norm.js | 3264 -> 3256 : +0.245% | 1592 -> 1592 : 0.000% | 0.730 -> 0.728 : +0.210% | 
raytrace.js | 22424 -> 22520 : -0.428% | 5000 -> 4740 : **+5.200%** | 2.569 -> 2.649 : -3.113% | 
richards.js | 8568 -> 8560 : +0.093% | 2140 -> 2180 : -1.869% | 0.299 -> 0.298 : +0.260% | 
string-base64.js | 90104 -> 90104 : 0.000% | 1640 -> 1640 : 0.000% | 1.413 -> 1.405 : +0.550% | 
string-fasta.js | 4400 -> 4400 : 0.000% | 1576 -> 1576 : 0.000% | 3.365 -> 3.379 : -0.426% | 
Geometric mean: | -0.044% | +0.139% | -0.102% | 

Binary (bytes) | master(2240a9153a) | patch(496ae337fb) | Diff |
----: | ----: | ----: | ----: |
size | 226968 | 226968 | 0 bytes |
.rodata | 20119 | 20119 | 0 bytes |
.dynstr | 433 | 433 | 0 bytes |
.rel.plt | 440 | 440 | 0 bytes |
.interp | 25 | 25 | 0 bytes |
.dynsym | 976 | 976 | 0 bytes |
.gnu.hash | 456 | 456 | 0 bytes |
.text | 199536 | 199576 | +40 bytes |
.comment | 85 | 85 | 0 bytes |
.shstrtab | 226 | 226 | 0 bytes |
.data | 8 | 8 | 0 bytes |
.ARM.exidx | 8 | 8 | 0 bytes |
.rel.dyn | 16 | 16 | 0 bytes |
.init | 12 | 12 | 0 bytes |
.got | 236 | 236 | 0 bytes |
.plt | 692 | 692 | 0 bytes |
.note.ABI-tag | 32 | 32 | 0 bytes |
.gnu.version_r | 64 | 64 | 0 bytes |
.bss | 1575096 | 1575096 | 0 bytes |
.fini | 8 | 8 | 0 bytes |
.hash | 400 | 400 | 0 bytes |
.gnu.version | 122 | 122 | 0 bytes |
.fini_array | 4 | 4 | 0 bytes |
.init_array | 4 | 4 | 0 bytes |
.dynamic | 248 | 248 | 0 bytes |
.eh_frame | 4 | 4 | 0 bytes |
.ARM.attributes | 53 | 53 | 0 bytes |

**Comment by rerobika** [comment]
About the numbers above:

In the benchmark tests the bytecode size is significantly decreased when `obj[number]` is used (1 byte/instruction), however this leads to a new memory layout and GC intensity which explains the "interesting" stack/memory consumption changes. Besides the benchmark result, I'd still title it as an improvement.

**Review by zherczeg — APPROVED** [review]
LGTM
Increase the byte code version please.

**Comment by rerobika** [comment]
@zherczeg Thanks I've increased the snapshot version.

**Review by ossy-szeged — APPROVED** [review]
LGTM

**Pull request merged**
