### PR TITLE
Update packages before installing them

### PR DESCRIPTION
**Pull request by rerobika**
JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by ossy-szeged** [comment]
It's strange that GH VMs aren't up-to-date and we have to update explicitly. Is it a known GH issue?

Otherwise LGTM (informal).

**Comment by rerobika** [comment]
@ossy-szeged I didn't found anything about it, but it is potentially due to the outdated VMs. So treat this PR as a workaround for this problem.

**Review by zherczeg — APPROVED** [review]
Fix the installation of gcc-multilib on ubuntu 18.04 #4388
Open LGTM

**Comment by akosthekiss** [comment]
Shouldn't all `apt install`s be prepended by an `apt update`, not only where gcc-multilib is installed? Ubuntu repos may evolve any time. GH VMs may get updated slower.

**Comment by lygstate** [comment]
> Shouldn't all `apt install`s be prepended by an `apt update`, not only where gcc-multilib is installed? Ubuntu repos may evolve any time. GH VMs may get updated slower.

make sense.

**Comment by rerobika** [comment]
Sure, the PR is updated.

**Review by akosthekiss — APPROVED** [review]
LGTM

**Comment by akosthekiss** [comment]
Looks like master is green again. Yay!

**Pull request merged**
