### PR TITLE
Fixed error handling during processing promise jobs

### LINKED ISSUE #2065: Assertion 'object_p->type_flags_refs >= ECMA_OBJECT_REF_ONE' failed in ecma_deref_object
###### Jerry version:

```
Checked revision: d9cc3fd
Build command: ./tools/build.py --clean --debug  --profile=es2015-subset
```
###### OS:

```
Ubuntu 16.04.3 LTS
```
###### Test case:

```javascript
var a = Promise.prototype;
for (var i = 0; i < 200; i++)
{
    Promise.race([a]).then();
}
```

###### Backtrace:

```
ICE: Assertion 'object_p->type_flags_refs >= ECMA_OBJECT_REF_ONE' failed at jerryscript/jerry-core/ecma/base/ecma-gc.c(ecma_deref_object):143.
Error: ERR_FAILED_INTERNAL_ASSERTION
bt
#0  0x000000000059e248 in raise ()
#1  0x000000000059e45a in abort ()
#2  0x000000000057e4bd in jerry_port_fatal (code=25351) at jerryscript/jerry-port/default/default-fatal.c:71
#3  0x00000000004faeef in jerry_fatal (code=<optimized out>) at jerryscript/jerry-core/jrt/jrt-fatals.c:60
#4  0x00000000004fafe0 in jerry_assert_fail (assertion=0x6 <error: Cannot access memory at address 0x6>, file=0x59e248 <raise+56> "H=", function=0xb01880 "\200\030\260", line=<optimized out>) at jerryscript/jerry-core/jrt/jrt-fatals.c:84
#5  0x0000000000418742 in ecma_deref_object (object_p=<optimized out>) at jerryscript/jerry-core/ecma/base/ecma-gc.c:143
#6  0x00000000004dd48d in ecma_process_promise_reaction_job (obj_p=0xa87920 <jerry_global_heap+31728>) at jerryscript/jerry-core/ecma/operations/ecma-jobqueue.c:210
#7  0x00000000004ddcf9 in ecma_process_all_enqueued_jobs () at jerryscript/jerry-core/ecma/operations/ecma-jobqueue.c:344
#8  0x0000000000402f85 in main (argc=<optimized out>, argv=0x7fffffffd188) at jerryscript/jerry-main/main-unix.c:900
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2065 and adds a test case for it.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by rerobika** [comment]
Cc: @jiangzidong

**Comment by rerobika** [comment]
Okay, Travis revealed a new potential unhandled corner case, I'm working on it.

**Comment by rerobika** [comment]
This error has been solved by #2115. I close this PR.

**Comment by jiangzidong** [comment]
@rerobika Sorry that I missed your PR and the issue before (maybe to many mails that days). I just found them...

**Pull request closed without merging**
