### PR TITLE
Adds support for compiling with MSYS and MINGW under windows

### PR DESCRIPTION
**Pull request by webmaster442**
JerryScript-DCO-1.0-Signed-off-by: Ruzsinszki Gábor ruzsinszki.gabor@gmail.com

### CODE REVIEW

**Comment by akosthekiss** [comment]
Please, DO NOT close the PR every time you make a change. Just (force) push your new commit(s) to the same branch you used to open the PR.

**Comment by webmaster442** [comment]
> 
> 
> Please, DO NOT close the PR every time you make a change. Just (force) push your new commit(s) to the same branch you used to open the PR.

Sorry, First I  didn't got the Signed-off stuff in the commit right.

**Comment by akosthekiss** [comment]
> Sorry, First I didn't got the Signed-off stuff in the commit right.

Well, everyone makes mistakes. I sometimes forget the signoff, sometimes I don't forget it but simply get it wrong. Sometimes I forget the style check, or for whatever other reason, the CI goes red. But that was not my point.

My point is that unless you want to abandon your PR, don't close it. If you get the signoff wrong, fix it locally in your branch and push it to github. If you get the builds fail, fix it locally and push it to github. If you get a review from one of the maintainers requesting changes, perform the changes, commit and push the branch to github. Github will catch the push to the branch and it will automatically update the PR.

**Comment by ossy-szeged** [comment]
LGTM (informal)

**Pull request merged**
