### PR TITLE
Update the webpage

### PR DESCRIPTION
**Pull request by bzsolt**

### CODE REVIEW

**Comment by akosthekiss** [comment]
> Hi, you need sign-off,
> Format:
> 
> JerryScript-DCO-1.0-Signed-off-by: Example Name [example@example.com](mailto:example@example.com)

?

**Review by akosthekiss — APPROVED** [review]
LGTM

**Comment by ossy-szeged** [comment]
> Hi, you need sign-off,
> Format:
> 
> JerryScript-DCO-1.0-Signed-off-by: Example Name [example@example.com](mailto:example@example.com)

The patch already contains the necessary sign-off part.

**Review by ossy-szeged — APPROVED** [review]
LGTM

**Comment by lygstate** [comment]
> > Hi, you need sign-off,
> > Format:
> > JerryScript-DCO-1.0-Signed-off-by: Example Name [example@example.com](mailto:example@example.com)
> 
> The patch already contains the necessary sign-off part.

OK then

**Pull request merged**
