### PR TITLE
Get rid of `? true : false`

### PR DESCRIPTION
**Pull request by akosthekiss**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
I would like to see the effect on some exotic compiler environments. This has never caused any issues on Linux.

**Comment by akosthekiss** [comment]
@zherczeg Please, name those exotic compiler environments and also those from whom you expect the feedback. Right now, I see no setup where `? true : false` would be a sensible construct.

**Comment by LaszloLango** [comment]
LGTM if builds with in the environment @rtakacs use. @rtakacs please validate the patch.

**Comment by rtakacs** [comment]
I've tried out JSRemoteTest with this branch:

```
js-remote-test/deps/jerryscript/jerry-core/parser/js/js-lexer.c: In function 'lexer_construct_regexp_object':
js-remote-test/deps/jerryscript/jerry-core/ecma/base/ecma-globals.h:246:3: error: conversion to '_Bool8' from 'long int' may alter its value [-Werror=conversion]
   (JERRY_UNLIKELY ((value) == ECMA_VALUE_ERROR))
   ^
js-remote-test/deps/jerryscript/jerry-core/parser/js/js-lexer.c:2178:19: note: in expansion of macro 'ECMA_IS_VALUE_ERROR'
   bool is_throw = ECMA_IS_VALUE_ERROR (completion_value);
```

**Comment by rtakacs** [comment]
More detailed output: https://gist.github.com/rtakacs/0de9c0fa1b9a1b4b80162e435dd8f947

**Comment by akosthekiss** [comment]
@rtakacs I've updated the PR. I did not expect `JERRY_UNLIKELY` (the expression behind `ECMA_IS_VALUE_ERROR`) to yield result incompatible with `bool`. Now, that result is also cast explicitly. Could you please run a new round of tests?

**Comment by rtakacs** [comment]
@akosthekiss Okay, it works now :)

LGTM (informal)

**Comment by akosthekiss** [comment]
Thanks, @rtakacs

**Pull request merged**
