### PR TITLE
Update Zephyr RTOS port for Zephyr 1.10 release (squashed)

### PR DESCRIPTION
**Pull request by pfalcon**
In 1.10, Zephyr RTOS switched to CMake as means to generate application
makefiles. Consequently, drop Makefile, and introduce CMakeLists.txt,
and update master Makefile.zephyr accordingly.

With these changes, take a chance to make following "cosmetic" changes:

1. Make "qemu_x86" board target the default instead of "arduino_101".
Arduino 101 is just one of the boards of many supported by Zephyr
(and thus JerryScript port), while qemu_x86 is something everyone has.

2. Zephyr make target to run QEMU switched from "qemu" to "run".

3. Don't rely that there's zephyr.strip, it's presence is now
board-dependent. The most we can rely on is zephyr.elf.

targets: zephyr: Remove deprecated prj.mdef file.

MDEF files have been deprecated and ignored for few Zephyr releases.

targets: zephyr: Increase main (i.e. interpreter) thread stack size.

qemu_x86 target now has stack guard enabled by default and it trips with
the default stack size. Set it to 2K for now.

targets: zephyr: Makefile.travis: Update for Zephyr 1.10.

Zephyr 1.10 requires SDK 0.9.2 and CMake 3.8.2.

Also, don't hardcode CC path, it depends on a board and choosed
automatically by Zephyr build system.

JerryScript-DCO-1.0-Signed-off-by: Paul Sokolovsky paul.sokolovsky@linaro.org

### CODE REVIEW

**Comment by pfalcon** [comment]
This is resubmit of https://github.com/jerryscript-project/jerryscript/pull/2120 , squashed on the request in https://github.com/jerryscript-project/jerryscript/pull/2120#pullrequestreview-82907004

@LaszloLango : Please have a look.

**Comment by robertsipka** [comment]
LGTM (informally)

**Comment by pfalcon** [comment]
@LaszloLango : Ping, should be good to merge then?

**Comment by LaszloLango** [comment]
@pfalcon it needs one more approval from a maintainer. Unfortunately @robertsipka is only a committer this is why he can give you only an informal review.

**Comment by pfalcon** [comment]
Ok, thanks, pinging @akosthekiss as the author of Zephyr CI code.

**Comment by pfalcon** [comment]
Thanks!

**Pull request merged**
