### PR TITLE
 Fix a typo in case of single thread/process execution in test262 harness

### PR DESCRIPTION
**Pull request by galpeter**

### CODE REVIEW

**Comment by ossy-szeged** [comment]
I think we won't need it after https://github.com/jerryscript-project/jerryscript/commit/3b7409f3a7311430bb4e5e1f065e386b0db71d9a . But let's wait a little bit before closing this PR.
Otherwise the typo fix in run function should be landed.

**Comment by galpeter** [comment]
Updated PR to only have the typo fix.

**Comment by ossy-szeged** [comment]
LGTM (informal)

**Review by dbatyai — APPROVED** [review]
LGTM

**Review by rerobika — APPROVED** [review]
LGTM

**Pull request merged**
