### PR TITLE
Enable the already fixed test cases

### PR DESCRIPTION
**Pull request by matedabis**
Uncomment already fixed asserts.

JerryScript-DCO-1.0-Signed-off-by: Mate Dabis mdabis@inf.u-szeged.hu

### CODE REVIEW

**Comment by akosthekiss** [comment]
I see the improvements to equality.js but what's the point of all the other "negative tests" in the other files? What test coverage does it improve?

**Comment by matedabis** [comment]
@akosthekiss It improves the test coverage because it checks if these tests also work in the opposite way. There was not so many negative tests in the tests/jerry before, and with these test, I test cases that was not really tested before.

**Comment by akosthekiss** [comment]
@matedabis I'd like to see this coverage increase supported by numbers. Could you please share coverage results (and how they were measured)?

My doubts come from the following observations:
- The tests already contain `if (true && false && fail())`
- The new addition is `if ((true && false && fail()) != false)`
- Assuming that `true && false && fail()` behaves consistently, this new code only tests `true != false`
- But that's already tested in test262/.../S8.3_A3.js.

This is just an example but there are similar constructs everywhere.

**Comment by akosthekiss** [comment]
@matedabis Self correction. The new code only tests `false != false`, which is tested in .../S11.9.2_A3.1.js and S11.9.5_A3.js

**Comment by matedabis** [comment]
@akosthekiss Okay, I will split it.

**Comment by matedabis** [comment]
@akiss Now this PR only contains the changes of equality.js. I will put the other changes on @repasics's branch.

**Comment by akosthekiss** [comment]
@matedabis Please, tag me (@akosthekiss) in communications.

**Pull request merged**
