### PR TITLE
Fix implicit 'double' conversion reported by Clang 12.0.0

### PR DESCRIPTION
**Pull request by kaadam**
JerryScript-DCO-1.0-Signed-off-by: Adam Kallai kadam@inf.u-szeged.hu

### CODE REVIEW

**Comment by kaadam** [comment]
A snippet of the error:

/home/kadam/jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:564:17: error: implicit conversion from 'ecma_length_t' (aka 'unsigned long') to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
  JERRY_ASSERT (number <= ECMA_NUMBER_MAX_SAFE_INTEGER);
                ^~~~~~ ~~
/home/kadam/jerryscript/jerry-core/jrt/jrt.h:88:21: note: expanded from macro 'JERRY_ASSERT'
      JERRY_UNUSED (x); \
                    ^
/home/kadam/jerryscript/jerry-core/jrt/jrt.h:34:34: note: expanded from macro 'JERRY_UNUSED'
#define JERRY_UNUSED(x) ((void) (x))
                                 ^
/home/kadam/jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:2971:17: error: implicit conversion from 'ecma_length_t' (aka 'unsigned long') to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]
  JERRY_ASSERT (index <= ECMA_NUMBER_MAX_SAFE_INTEGER);
                ^~~~~ ~~
/home/kadam/jerryscript/jerry-core/jrt/jrt.h:88:21: note: expanded from macro 'JERRY_ASSERT'
      JERRY_UNUSED (x); \
                    ^
/home/kadam/jerryscript/jerry-core/jrt/jrt.h:34:34: note: expanded from macro 'JERRY_UNUSED'
#define JERRY_UNUSED(x) ((void) (x))
                                 ^
2 errors generated.

Could anyone take a look at this? Thanks!

**Comment by ossy-szeged** [comment]
LGTM (informal)

**Review by rerobika — APPROVED** [review]
LGTM

**Review by akosthekiss — APPROVED** [review]
LGTM

**Pull request merged**
