### PR TITLE
Jerryscript could have a new target: LiteOS.

### PR DESCRIPTION
**Pull request by BaikalHu**
JerryScript-DCO-1.0-Signed-off-by: BaikalHu baikalhu@foxmail.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
Why did you close the original PR (#1922)?

**Comment by BaikalHu** [comment]
I thought no one will be aware the original PR because it took several days.

**Comment by LaszloLango** [comment]
@BaikalHu feel free to contact us on IRC (#jerryscript) or just write a comment on the PR, if you would like to request a new review after an update. :) Sorry for the inactivity. Most of us were out of office in the last two-three weeks. I think it would be better to re-open the old PR, because it has previous reviews and we lost the history this way.

**Comment by BaikalHu** [comment]
@LaszloLango , so  could I re-open the old PR and close this one?

**Comment by LaszloLango** [comment]
@BaikalHu, yes please.

**Pull request closed without merging**
