### PR TITLE
Remove unnecessary if statement

### PR DESCRIPTION
**Pull request by tkeri**
JerryScript-DCO-1.0-Signed-off-by: Tamas Keri tkeri@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
"Remote"? I think you wanted to write "Remove". :)

**Comment by zherczeg** [comment]
I am curious why this is unused?

**Comment by tkeri** [comment]
Because the **JERRY_CONTEXT (jmem_heap_list_skip_p)** will overwrite in L521: https://github.com/jerryscript-project/jerryscript/pull/1978/commits/ef7e0ee51e9fcd8865c0f3cd747ca2928e80245b#diff-b6c30e4774fc34221a39be31b8bda838R515  .

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
