### PR TITLE
target: mbedos5: Update to mbed OS 5.2.3

### PR DESCRIPTION
**Pull request by janjongboom**
Update mbed OS target to latest version of mbed OS (5.2.3). Also rename all files in jerryscript-mbed-drivers/ to include -js.cpp, as our build tools now generate warnings for C++ files with the same name. mbed-events library is now mainlined, so no longer required to pull this library in as a separate dependency. ``main.cpp`` is auto-generated and should not be included in this repository.

JerryScript-DCO-1.0-Signed-off-by: Jan Jongboom janjongboom@gmail.com

/cc @thegecko @matthewelse

Verified against:

- mbed-js-easy-connect
- mbed-js-example
- mbed-js-repl-example
- mbed-js-ble-example

When switching to this branch for an existing mbed JS program, you might need to run:

```
$ cd build/jerryscript/targets/mbedos5
$ mbed deploy
$ rm -rf mbed-events
```

Although probably taken care off by gulp.

### CODE REVIEW

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Comment by zherczeg** [comment]
@thegecko @matthewelse please check this patch

**Comment by matthewelse** [comment]
@zherczeg LGTM, though looks like a few conflicts need resolving (I think these might be the copyright notices)

**Comment by janjongboom** [comment]
@zherczeg @LaszloLango Rebased against upstream/master, but fails now with (gcc 4.9):

```
[Warning] ecma-arraybuffer-object.h@37,1: always_inline function might not be inlinable [-Wattributes]
[Warning] ecma-arraybuffer-object.h@39,1: always_inline function might not be inlinable [-Wattributes]
[Error] ecma-arraybuffer-object.h@39,0: inlining failed in call to always_inline 'ecma_arraybuffer_get_length': function body not available
[Error] ecma-builtin-arraybuffer-prototype.c@64,21: called from here
[ERROR] In file included from ../../jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c:22:0:
../../jerry-core/ecma/operations/ecma-arraybuffer-object.h:37:1: warning: always_inline function might not be inlinable [-Wattributes]
 ecma_arraybuffer_get_buffer (ecma_object_t *) __attr_pure___ __attr_always_inline___;
 ^
../../jerry-core/ecma/operations/ecma-arraybuffer-object.h:39:1: warning: always_inline function might not be inlinable [-Wattributes]
 ecma_arraybuffer_get_length (ecma_object_t *) __attr_pure___ __attr_always_inline___;
 ^
../../jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c: In function 'ecma_builtin_arraybuffer_prototype_bytelength_getter':
../../jerry-core/ecma/operations/ecma-arraybuffer-object.h:39:1: error: inlining failed in call to always_inline 'ecma_arraybuffer_get_length': function body not available
../../jerry-core/ecma/builtin-objects/ecma-builtin-arraybuffer-prototype.c:64:21: error: called from here
       ecma_length_t len = ecma_arraybuffer_get_length (object_p);
```

Removing the always inline from `ecma_arraybuffer_get_buffer` and `ecma_arraybuffer_get_length` makes it build again... Has something changed here recently?

**Comment by jiangzidong** [comment]
@janjongboom we extended the builtin object recently. 
I think it's because the definition of inline functions (ecma_arraybuffer_get_buffer and ecma_arraybuffer_get_length) are in other source files. [link](http://stackoverflow.com/questions/6434221/gcc-and-inlining-c-functions-declared-in-other-files-the-function-body-not-ava)
My gcc version is 4.8.4 and didnt throw error.

I think there are 2 solutions
* remove the inline
* put the defination into the header file, and set the function static

I prefer removing the inline flag. 

Should I post a new PR, or janjongboom fix it in his PR? @LaszloLango @zherczeg

**Comment by janjongboom** [comment]
@jiangzidong Preferably in a new PR.

**Comment by zherczeg** [comment]
@jiangzidong ok, lets remove the inline flag. I hope the compiler will be clever enough to do inlining automatically. Please open a new PR since this seems an unrelated change.

**Comment by jiangzidong** [comment]
@janjongboom @zherczeg the new PR is #1484

**Comment by janjongboom** [comment]
Rebased again. Builds and works if #1485 is landed too.

**Comment by tilmannOSG** [comment]
LGTM, I think we can merge this right after #1485 goes in (which should happen very soon).

**Pull request merged**
