### PR TITLE
fix building without BIGINT

### PR DESCRIPTION
**Pull request by aksdfauytv**
someone forgot ifdef for bigint

JerryScript-DCO-1.0-Signed-off-by: Maciej Musiał xt1@o2.pl

### CODE REVIEW

**Review by robertsipka — CHANGES_REQUESTED** [review]
Thanks, the fix is ​​necessary but currently it is just a half-solution. Please guard the bigint related usages  in `ecma_set_typedarray_element` method as well.

**Comment by aksdfauytv** [comment]
> Thanks, the fix is ​​necessary but currently it is just a half-solution. Please guard the bigint related usages in `ecma_set_typedarray_element` method as well.

Can you elaborate?

**Comment by robertsipka** [comment]
> > Thanks, the fix is ​​necessary but currently it is just a half-solution. Please guard the bigint related usages in `ecma_set_typedarray_element` method as well.
> 
> Can you elaborate?

As I saw, the `ecma_bigint_to_bigint` call is not guarded inside the mentioned function neither, but it should be. You can receive a more detailed error message if you run the build without the bigint builtin.

**Comment by aksdfauytv** [comment]
Obviously, that's why I created this pull request, it adds the guard. But you flagged the pull request as "Changes requested", so that's what I'm asking you about, what additional changes do you need?

**Comment by ossy-szeged** [comment]
There is at least one more build fail related to ecma_bigint_to_bigint:

jerryscript/jerry-core/ecma/operations/ecma-atomics-object.c:171:11: error: implicit declaration of function ‘ecma_bigint_to_bigint’; did you mean ‘jerry_bigint_to_digits’? [-Werror=implicit-function-declaration]
  171 |     val = ecma_bigint_to_bigint (value, true);
      |           ^~~~~~~~~~~~~~~~~~~~~

**Comment by robertsipka** [comment]
Although the additional bug is still present in your branch, within that line that @ossy-szeged marked, please rebase it onto master, and you will see which function contains the issue and what I mentioned to you and which where you also needs to add guards if the mentioned builtin is not enabled. You just need to follow the instructions you wrote in your PR, meaning build the project with the bigint builtin disabled, you will see what is required and why i requested changes...

**Comment by aksdfauytv** [comment]
I see, I didn't notice the issue in ecma-atomics-object.c, because I was building with atomics disabled. Thank you for pointing it out.

**Review by ossy-szeged — APPROVED** [review]

**Review by robertsipka — APPROVED** [review]

**Comment by LaszloLango** [comment]
After #5166 this is fixes the build, no need for changes.

**Review by LaszloLango — APPROVED** [review]

**Comment by ossy-szeged** [comment]
Let's merge it as is, atomics part is fixed in #5166

**Pull request merged**
