### PR TITLE
Always define debugger-related opcodes

### PR DESCRIPTION
**Pull request by bzsolt**
This change makes the generated snapshot independent from buildconfig.

JerryScript-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
IMHO we should update the snapshot version too

**Comment by bzsolt** [comment]
@LaszloLango I've updated the snapshot-version too.

**Comment by jiangzidong** [comment]
@bzsolt Could you please explain the reason of the patch?

After the patch, the snapshot of a js code still depends on the `FEATURE_DEBUGGER`. e.g. only when FEATURE_DEBUGGER is enabled, the bytecode will insert CBC_BREAKPOINT_DISABLED at the end of each statement. am I right?

**Comment by zherczeg** [comment]
The problem was that the snapshot byte code generated when the debugger is enabled (although not used) is different from when the debugger is disabled. The opposite is also true, when you enable debugger you cannot execute a snapshot which was generated by a JerryScript without a debugger.

**Comment by jiangzidong** [comment]
I see, after the patch, all snapshot (no matter generated w/ or w/o debugger) can be executed in all jerry.

```
The opposite is also true, when you enable debugger you cannot execute a snapshot which was generated by a JerryScript without a debugger.
```
Is that a typo?
I think the case in your example can work without the patch. Only when you **disable** debugger, you cannot execute snapshot generated **with a debugger**.

**Comment by zherczeg** [comment]
:) I don't understand your sentence, but probably we are thinking the same thing.

A: jerry with debugger
B: jerry without debugger

Combinations: [generates snapshot, executes snapshot] 

Old: [A,A] [B,B]
New: [A,A] [B,B] [A,B] [B,A]

**Comment by jiangzidong** [comment]
will [B, A] fail before the patch? Let's me have a quick test

**Comment by jiangzidong** [comment]
Oh, I see, the debugger related cbc codes are insert into the middle of the opcode list (not the tail). You're right. :)

**Pull request merged**
