### PR TITLE
Check if property is not found before delete it.

### PR DESCRIPTION
**Pull request by jiangzidong**
Check if property is not found before delete it.

Fix issue #1633 

JerryScript-DCO-1.0-Signed-off-by: Zidong Jiang zidong.jiang@intel.com

### CODE REVIEW

**Comment by jiangzidong** [comment]
I will add the test case after #1632 is landed

**Comment by zherczeg** [comment]
I would prefer to add real description to these commits not Fix issue. In the description the Fix issue should be present, but not in the title.

**Comment by zherczeg** [comment]
A test file is still missing :)

**Comment by jiangzidong** [comment]
@zherczeg I know, I will add the case as soon as #1627 merged, since #1627 contain the jerry-tests framework for es2015. Sorry for the dalay

**Comment by jiangzidong** [comment]
@zherczeg The test file is added.

**Pull request merged**
