### PR TITLE
Rework frame context

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
The patch increase the stack consumption by exactly 16 bytes in all cases. I think this is acceptable.

Benchmark | Stack (bytes) |
----: | ----: | 
3d-cube.js | 16208 -> 16224 : -0.099% | 
3d-morph.js | 1600 -> 1616 : -1.000% | 
3d-raytrace.js | 2868 -> 2884 : -0.558% | 
access-binary-trees.js | 3832 -> 3848 : -0.418% | 
access-fannkuch.js | 1672 -> 1688 : -0.957% | 
access-nbody.js | 1808 -> 1824 : -0.885% | 
bitops-3bit-bits-in-byte.js | 1616 -> 1632 : -0.990% | 
bitops-bits-in-byte.js | 1616 -> 1632 : -0.990% | 
bitops-bitwise-and.js | 1368 -> 1384 : -1.170% | 
bitops-nsieve-bits.js | 1616 -> 1632 : -0.990% | 
controlflow-recursive.js | 73816 -> 73832 : -0.022% | 
crypto-aes.js | 2600 -> 2616 : -0.615% | 
crypto-md5.js | 1936 -> 1952 : -0.826% | 
crypto-sha1.js | 1744 -> 1760 : -0.917% | 
crypto.js | 3580 -> 3596 : -0.447% | 
date-format-tofte.js | 2192 -> 2208 : -0.730% | 
date-format-xparb.js | 2776 -> 2792 : -0.576% | 
deltablue.js | 4156 -> 4172 : -0.385% | 
math-cordic.js | 1616 -> 1632 : -0.990% | 
math-partial-sums.js | 1592 -> 1608 : -1.005% | 
math-spectral-norm.js | 1624 -> 1640 : -0.985% | 
raytrace.js | 5672 -> 5688 : -0.282% | 
richards.js | 2452 -> 2468 : -0.653% | 
string-base64.js | 1664 -> 1680 : -0.962% | 
string-fasta.js | 1600 -> 1616 : -1.000% | 
Geometric mean: | -0.738% | 

116 bytes increase in text, no other changes

**Comment by zherczeg** [comment]
Benchmark | Stack (bytes) |
----: | ----: | 
3d-cube.js | 16208 -> 15784 : **+2.616%** | 
3d-morph.js | 1600 -> 1616 : -1.000% | 
3d-raytrace.js | 2868 -> 2828 : **+1.395%** | 
access-binary-trees.js | 3832 -> 3768 : **+1.670%** | 
access-fannkuch.js | 1672 -> 1688 : -0.957% | 
access-nbody.js | 1808 -> 1824 : -0.885% | 
bitops-3bit-bits-in-byte.js | 1616 -> 1632 : -0.990% | 
bitops-bits-in-byte.js | 1616 -> 1632 : -0.990% | 
bitops-bitwise-and.js | 1368 -> 1384 : -1.170% | 
bitops-nsieve-bits.js | 1616 -> 1632 : -0.990% | 
controlflow-recursive.js | 73816 -> 71792 : **+2.742%** | 
crypto-aes.js | 2600 -> 2576 : +0.923% | 
crypto-md5.js | 1936 -> 1912 : **+1.240%** | 
crypto-sha1.js | 1744 -> 1760 : -0.917% | 
crypto.js | 3580 -> 3524 : **+1.564%** | 
date-format-tofte.js | 2192 -> 2176 : +0.730% | 
date-format-xparb.js | 2776 -> 2768 : +0.288% | 
deltablue.js | 4156 -> 4068 : **+2.117%** | 
math-cordic.js | 1616 -> 1632 : -0.990% | 
math-partial-sums.js | 1592 -> 1608 : -1.005% | 
math-spectral-norm.js | 1624 -> 1632 : -0.493% | 
raytrace.js | 5672 -> 5568 : **+1.834%** | 
richards.js | 2452 -> 2412 : **+1.631%** | 
string-base64.js | 1664 -> 1680 : -0.962% | 
string-fasta.js | 1600 -> 1616 : -1.000% | 
Geometric mean: | +0.265% | 

This will be the final variant. It still has the 16 byte increase, but in some cases the stack usage is reduced.

**Review by rerobika — APPROVED** [review]
LGTM

**Review by dbatyai — APPROVED** [review]
LGTM

**Pull request merged**
