### PR TITLE
Add test result information to the README.md

### PR DESCRIPTION
**Pull request by yichoi**
JerryScript-DCO-1.0-Signed-off-by: Youngil Choi duddlf.choi@samsung.com

### CODE REVIEW

**Comment by yichoi** [comment]
no more comments?

**Comment by LaszloLango** [comment]
"404 - File not found"

**Comment by yichoi** [comment]
@LaszloLango, resolved
@rtakacs, please check it again

**Comment by rtakacs** [comment]
The images are available. LGTM. However currently just the iotjs status logos are updated automatically (by the testrunner). I'm going to support that for JerryScript.

**Comment by yichoi** [comment]
@rtakacs ok. that's great

**Comment by rtakacs** [comment]
Okay, I'm finished. Now, the referred logos are automatically updated. We can land this patch :)

**Pull request merged**
