### PR TITLE
Avoid using an unitialized variable

### PR DESCRIPTION
**Pull request by robertsipka**
@DanielBallaSZTE : This bug is appeared after your PR (#2191). Please check that this patch covers your original intent.

### CODE REVIEW

**Comment by zherczeg** [comment]
I think the issue is not "avoiding an uninitialized variable", but the code was simply wrong. So please change the description. Also pleas add test case since it seems this is not tested.

**Comment by robertsipka** [comment]
I think both. The code was wrong, but also allowed that if the first part of the condition is false then the uninitialized value of the `code_unit` is used. Besides this I agree with you, I will rename it, and add test cases also.

**Comment by zherczeg** [comment]
Please add a test case. I think an eval should do it.

**Comment by robertsipka** [comment]
@zherczeg : Sorry for the late response. I've looked over it and actually I do not know what to check that we have not checked yet. The `jerry` returns with SyntaxError in case of invalid unicode escape sequence, which is an expected behaviour. In #2191, a test case has already added which covers the #2180 and #2192 issues, but it was a wrong and a partial fix, the problem is still exist in some cases without this patch, e.g. the following input : `JSON.parse('"' + '\\u23');` will cause the same issue in the current master. Should I add another test with the input above?

**Comment by robertsipka** [comment]
#2201 also fixes this bug, so I am closing this PR.

**Pull request closed without merging**
