### PR TITLE
Simplify run-time feature checks in unit tests

### PR DESCRIPTION
**Pull request by akosthekiss**
JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
IMHO the unit tests should use the related API function instead: http://jerryscript.net/api-reference/#jerry_is_feature_enabled

**Comment by akosthekiss** [comment]
During some development, I've run into this:
```
/home/travis/build/akosthekiss/jerryscript/tests/unit-core/test-typedarray.c: In function ‘main’:
/home/travis/build/akosthekiss/jerryscript/tests/unit-core/test-typedarray.c:475:7: error: ‘byte_length’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
       TEST_ASSERT (byte_length == element_count);
       ^
/home/travis/build/akosthekiss/jerryscript/tests/unit-core/test-typedarray.c:472:22: note: ‘byte_length’ was declared here
       jerry_length_t byte_length;
                      ^
lto1: all warnings being treated as errors
lto-wrapper: /usr/bin/gcc returned 1 exit status
/usr/bin/ld: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

It's strange that this hasn't appeared before, but the compiler is actually right. If jerry-core is built with the es5.1 profile, the body of some API functions is macrod out to be dummy. But some of them have out parameters, which are not filled in in this case. And LTO correctly recognizes this when jerry-core is linked to the unit tests. (Note: there are runtime feature checks in the unit tests, but the compiler cannot infer info from such checks.)

In the above example, the following code causes the problem:
```c
jerry_value_t buffer = jerry_get_typedarray_buffer (array, &offset, &byte_length);
TEST_ASSERT (byte_length == element_count);
```

@LaszloLango I'm not sure whether calling `jerry_is_feature_enabled` would help the LTO problem as that's also a runtime check.

**Comment by akosthekiss** [comment]
BTW have y'all seen the appveyor checking out on the PR? :) ( @lygstate @yichoi )

**Comment by akosthekiss** [comment]
It has turned out that the simpler `jerry_is_feature_enabled` approach worked as well. Thanks for the tip @LaszloLango . PR updated

**Comment by lygstate** [comment]
see it need a badge on the home Page

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
