### PR TITLE
target: mbedos5: Added DigitalIn & Serial js bindings

### PR DESCRIPTION
**Pull request by fluentart**
This is now working:

```
var a = new DigitalIn(BUTTON1); 
print(a.read());
```

Also added the other missing class constructors to lib_drivers.h as commented out lines. Lets get them all done!

JerryScript-DCO-1.0-Signed-off-by: Rouan van der Ende rouan.vanderende@iotnxt.com

### CODE REVIEW

**Comment by zherczeg** [comment]
@janjongboom please check this patch

**Comment by fluentart** [comment]
Thank you @zherczeg I've also now done:

```
Serial(tx,rx,baud)
Serial.baud()
Serial.putc()
Serial.getc()
Serial.writable()
Serial.readable()
```
Will do a commit now.

**Comment by fluentart** [comment]
I've been struggling to get Serial.attach() to work.
As soon as I send a byte to the board to trigger the interrupt I get this error:

`CMSIS-RTOS error: ISR Queue overflow (status: 0x2, task ID: 0x0, object ID: 0x20001240)`

If anyone can add this function it would be much appreciated.

**Comment by akosthekiss** [comment]
@fluentart a technical note to the pull request: it seems that you have opened the PR from your master which you also use for development. Now, there are already 4 commits stacked on each other with somewhat independent changes. The suggested way for contributing to the project is to have independent well-scoped features or pull requests in separate PR-s 1 commit each. Therefore it is a good practice not to use your master to open PR from but to have separate branches for the PRs. This way, each branch can evolve in its own pace as reviews start flowing in. And you can also keep your master in sync with the project's master easier.

The second thing is that you'll have to sign all your commits by adding a line at the end of the commit message:
```
JerryScript-DCO-1.0-Signed-off-by: Your Own Name your.own@email.address
```

All this is described in the contribution guidelines at https://github.com/jerryscript-project/jerryscript/blob/master/CONTRIBUTING.md . And you can also take a look at existing commits for signature lines at https://github.com/jerryscript-project/jerryscript/commits/master .

Note to ourselves: Travis should have warned about missing DCO signoff but Travis hasn't been running at all for any of the commits.

**Comment by fluentart** [comment]
Thanks @akosthekiss it wasnt clear if this message:
`JerryScript-DCO-1.0-Signed-off-by: Rouan van der Ende rouan.vanderende@iotnxt.com` 
should have been on the git commit or on the PR comment. Well, I've now moved on to Zephyr for now, you are free to use the code or not.

**Comment by akosthekiss** [comment]
@fluentart if you are abandoning the PR, please close it. "you are free to use the code or not" is not how the project works. As per project governance rules in place _Code without a proper signoff cannot be merged into the mainline_ (see: https://github.com/jerryscript-project/jerryscript/blob/master/DCO.md). If you will not add DCO sign-off and will not follow up reviews, we will not be able to use your contribution.

**Pull request closed without merging**
