### PR TITLE
Add script to extract JerryScript version from headers

### PR DESCRIPTION
**Pull request by akosthekiss**
This can be used at configuration time to
- display version in diagnostics, and
- to write proper version number in pkgconfig files.

### CODE REVIEW

**Comment by akosthekiss** [comment]
Blocking on #4330 and #4331

**Review by rerobika — APPROVED** [review]
LGTM

**Comment by rerobika** [comment]
Please rebase.

**Comment by akosthekiss** [comment]
Previously blocking PRs have been landed. This PR is now rebased to latest master.

**Review by zherczeg — APPROVED** [review]
LGTM

**Pull request merged**
