### PR TITLE
Extend CI list with Github actions

### PR DESCRIPTION
**Pull request by rerobika**
JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by rerobika** [comment]
Note: the GitHub actions will only trigger after the PR got merged. The local results for this PR is available [here](https://github.com/rerobika/jerryscript/actions/runs/137367796 ).

**Comment by ossy-szeged** [comment]
The results are promising. I think we should split at least the ARM and OSX tests to have more parallelizable jobs and smaller runtime.

**Comment by rerobika** [comment]
@ossy-szeged The longer runtimes on these jobs are due to the currently separated jerry-test-suite, which is going to be merged into the jerry-tests soon. I'd wait until these merge, after we can rebalance these jobs if needed.

**Comment by rerobika** [comment]
Needs to be updated after #3907 .

**Comment by rerobika** [comment]
Updated results: https://github.com/rerobika/jerryscript/actions/runs/138332968

**Pull request merged**
