### PR TITLE
Modify header file contains.

### PR DESCRIPTION
**Pull request by yangfasheng**
JerryScript-DCO-1.0-Signed-off-by: yangfasheng yangfasheng@rt-thread.com

### CODE REVIEW

**Comment by akosthekiss** [comment]
@yangfasheng Why have you closed #2459 and opened this PR with the exactly same contents?

**Comment by akosthekiss** [comment]
That's no reason for opening a new PR. When Travis CI signals a failure, one fixes the problem and pushes the new commit to the same branch. The PR on Github will be updated and Travis CI will re-run and give its new verdict.  If it's red again, iterate.

**Comment by yangfasheng** [comment]
So what do I need to do now.

**Comment by akosthekiss** [comment]
Now, nothing. We shall just wait for Travis CI to finish. But please don't duplicate PRs next time when a CI fails. Or when you get a change request in a review. Keep working on the same PR.

**Comment by yangfasheng** [comment]
Sorry, this is my first PR, so I don't know much about the process.

**Comment by akosthekiss** [comment]
FYI: https://guides.github.com/introduction/flow/

**Pull request merged**
