### PR TITLE
Make CI to be running by upgrade to all ubuntu that need  gcc-multilib to 20.04

### PR DESCRIPTION
**Pull request by lygstate**
JerryScript-DCO-1.0-Signed-off-by: Yonggang Luo luoyonggang@gmail.com

### CODE REVIEW

**Comment by akosthekiss** [comment]
Why is the Ubuntu version bump necessary?

**Comment by lygstate** [comment]
> Why is the Ubuntu version bump necessary?

Because on Ubuntu 18.04
`sudo apt-get install gcc-multilib` are always failing.

**Comment by ossy-szeged** [comment]
I think it is a GH issue. But I prefer #4388 as a workaround instead of migrating to Ubuntu 20.04.

**Comment by lygstate** [comment]
OK with that

**Pull request closed without merging**
