### PR TITLE
Use external handlers in tizenrt-artik05x target

### PR DESCRIPTION
**Pull request by glistening**
This patch includes followings:
- Use external handlers in jerry-ext.
- Make jerry_main similar to other ports. (including options)
- Merge jerry_port.c into jerry_main.c
  jerry_port is clearly out of jerry-core.

This patch not included following:
- Use jerry-libm, instead of system libm.
  It is already included.
  We choose to use jerry-libm since the result of cube-3d sunspider was inaccurate
  when using NuttX libm.
- Correct setjmp/longjmp implementation.
  I tried to bring the source from NuttX port.
  Unfortunately it does not work in tizenrt-artik05x as it is.
  I will take a closer look the code and make sure it works.

JerryScript-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com

### CODE REVIEW

**Comment by glistening** [comment]
Here is my next plan. I will port `setjmp/longjmp` on artik05x (cortex-r4). This architecture seems not support `VSTM` and so on, which were used in setjmp/longjmp on stm32f4 (cortex-m4). After landing this, I would like to close #1774. Then, I will make next step for porting promise on tizenrt-artik05x.

**Comment by yichoi** [comment]
LGTM

**Comment by robertsipka** [comment]
Just a question about the setjmp/longjmp implementation that may be a different from the source of the NuttX port. Is the hard-float mode enabled? The stm32f4 NuttX port's setjmp implementation expects that the hard-float mode is used and stores s16-s31 vfp registers to buffer, pointed with r0 register, and increases the register on size of stored data.

**Comment by robertsipka** [comment]
Sorry, I've just saw the #1823 issue, but the question is still valid, and it is concern both of the vstm and and vldm instructions.

**Pull request merged**
