### PR TITLE
Run CI on pushes and PRs to all branches

### PR DESCRIPTION
**Pull request by akosthekiss**
This helps testing on forks before opening a PR to the main repo.

JerryScript-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by akosthekiss** [comment]
This should help misunderstandings like #4393 and #4394 . This way, a push to any branch of a fork will trigger GH Actions on the fork, without the need for opening a PR to jerryscript-project/jerryscript (or to the fork's master branch).

**Comment by ossy-szeged** [comment]
LGTM (informal)

**Review by rerobika — APPROVED** [review]
LGTM

**Review by dbatyai — APPROVED** [review]
LGTM

**Pull request merged**
