### PR TITLE
Update NuttX target to releases/10.2

### PR DESCRIPTION
**Pull request by rtakacs**
* Updated NuttX from releases/9.0 to releases/10.2
  * Modified Makefile according to NuttX changes
* Updated README.md file
  * Added ROM File System and memory card usage descriptions as possible ways to share JavaScript input files with the device

### CODE REVIEW

**Review by robertsipka — APPROVED** [review]

**Review by robertsipka — APPROVED** [review]
LGTM, I've tried it, works like a charm.
Minor suggestions: More dependencies are already needed for the toolchain and the kconfig generator, so I would move up the following description: 
`https://github.com/apache/incubator-nuttx/blob/releases/10.2/Documentation/quickstart/install.rst`
stlink also has dependencies that are worth mentioning to install:
`gtk+-3.0 libusb-1.0-0-dev minicom`

**Comment by rtakacs** [comment]
@robertsipka I've added an `install-deps.sh` file that contains all the packages that are required by projects (NuttX, STLink) and serial communication.

**Comment by robertsipka** [comment]
even better, still looks good to me.

**Comment by rtakacs** [comment]
@robertsipka FYI, I've extended the `Makefile` with JerryScript compilation. In this case, `NuttX` automatically builds JerryScript as its dependency. (And that is not a different step for the user.)

**Review by dbatyai — APPROVED** [review]

**Pull request merged**
