### PR TITLE
Fix implicit 'double' conversion reported by Clang

### PR DESCRIPTION
**Pull request by kaadam**
JerryScript-DCO-1.0-Signed-off-by: Adam Kallai kadam@inf.u-szeged.hu

### CODE REVIEW

**Review by rerobika — APPROVED** [review]
LGTM

**Comment by kaadam** [comment]
Hi Folks,
It remained one conversion error reported by Clang, this CL aims to fix that. 
A snippet of the error:
/home/kadam/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c:1309:7: error: implicit conversion from 'ecma_length_t' (aka 'unsigned long') to 'double' may lose precision [-Werror
,-Wimplicit-int-float-conversion]                                                                         
  if (new_length > ECMA_NUMBER_MAX_SAFE_INTEGER)                                                               
      ^~~~~~~~~~
Could anyone take a look at that?

**Comment by ossy-szeged** [comment]
LGTM (informal)

**Review by zherczeg — APPROVED** [review]
LGTM

**Pull request merged**
