### PR TITLE
Update the webpage

### PR DESCRIPTION
**Pull request by bzsolt**

### CODE REVIEW

**Comment by rerobika** [comment]
Please wait for #3225 and include it if it lands.

**Comment by rerobika** [comment]
@bzsolt #3228 has landed, please update the PR.

**Comment by bzsolt** [comment]
What about the https://github.com/jerryscript-project/jerryscript/pull/3234? I can wait for that PR too :)

**Comment by rerobika** [comment]
@bzsolt Thanks for your patience, #3234 has just landed.

**Comment by bzsolt** [comment]
@rerobika Thanks, I've updated the PR.

**Pull request merged**
