### PR TITLE
Fix the exception handler bug

### PR DESCRIPTION
**Pull request by polaroi8d**
JerryScript-DCO-1.0-Signed-off-by: Levente Orban orbanl@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
Is it possible to write a test for this? It would great to add more description. "THE bug" is not obvious for me. :) What was the original problem?

**Comment by polaroi8d** [comment]
The original problem, if I want to evaluate a variable out of the scope in eval mode, the engine was not working. I don't think it need a new tests.

**Comment by zherczeg** [comment]
The strange thing is that existing tests don't catch this. Do we have a test which tests syntax error in eval?

**Comment by polaroi8d** [comment]
No.

**Comment by LaszloLango** [comment]
Please write a test and update the commit message.

**Pull request merged**
