### PR TITLE
Throw error for generator function class constructor

### PR DESCRIPTION
**Pull request by rerobika**
JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
I don't get why `class C { *["constructor"]() { } }` is supported

**Comment by rerobika** [comment]
> I don't get why `class C { *["constructor"]() { } }` is supported

To create a generator object from a generator function you should **call** the function, but you cannot invoke a class constructor without **new** keyword. However, I can agree that's a really weird example but due the this restriction no any runtime validation is required, since the generator function is inaccessible.

**Comment by zherczeg** [comment]
This works in firefox:
```
class C { ["constructor"]() { return 5; } }
(new C).constructor(); // 5
```

The code seems ok, but I would add two new testcases (with and without generator) for these.

**Comment by rerobika** [comment]
@zherczeg I've added these testcases.

**Comment by rerobika** [comment]
Note: The PR and the CI fail have nothing in common. The CI fail has been resolved in #3493.

**Pull request merged**
