### PR TITLE
Test various spaces in JavaScript source code.

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
Fixes #1554

**Comment by zherczeg** [comment]
I can rewrite the test to eval("\x...") form reviewers requests it.

**Comment by dbatyai** [comment]
Yes, please do so, I would very much prefer character codes.

**Comment by zherczeg** [comment]
The js test is replaced by an api test. I cannot directly create bytes in JS.

**Pull request merged**
