### PR TITLE
Travis CI - Put the NuttX/STM32F4 job to the allowed failures section

### PR DESCRIPTION
**Pull request by bzsolt**
Related issue: #2224

JerryScript-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by robertsipka** [comment]
This failures can not be resolved? Could not solve the problem by an `autoreconf -vfi` call before `./configure`?  If so, would it be an ugly workaround?

**Comment by bzsolt** [comment]
Unfortunately I don't have time for this, the mentioned command may resolves the problem. It is just a quick fix until the proper solution.

**Comment by robertsipka** [comment]
Ok, it is fine for me, but please check it later. LGTM (informally)

**Comment by LaszloLango** [comment]
@bzsolt I had some time, so I tried autoreconf and it works. IMHO it is a better fix, so a proposed an other PR: #2225

**Comment by bzsolt** [comment]
@LaszloLango thank you, I'm closing this PR due to https://github.com/jerryscript-project/jerryscript/pull/2225

**Pull request closed without merging**
