### PR TITLE
Rework module linking

### PR DESCRIPTION
**Pull request by zherczeg**
The module linking process from jerry_parse is moved out into a new jerry_module_link function, and jerry_parse is limited to create unlinked modules.

### CODE REVIEW

**Review by rerobika — APPROVED** [review]

**Comment by zherczeg** [comment]
Actually the ES2020 standard does not want to define the module resolving logic, it delegates everything to the user:

15.2.1.18 HostResolveImportedModule
15.2.1.16.1 Link ( ) Concrete Method

This is how v8 works (probably not a coincidence). Node.js for example heavily rely on this method, and maintain its own data set about the resolved modules and their dependencies.

**Comment by zherczeg** [comment]
An alternative could be to move the code from main to jerry-ext. That requires to design an api, so could be in a future patch.

**Comment by zherczeg** [comment]
The patch is reworked to use port for resolving. Please check the patch.

**Review by rerobika — APPROVED** [review]
still lgtm

**Review by dbatyai — APPROVED** [review]
LGTM

**Pull request merged**
