### PR TITLE
Add doxygen checker

### PR DESCRIPTION
**Pull request by LaszloLango**
* Fixed Doxygen issues
 * Updated Doxygen config
 * Added new script to test whether doxygen generation was successful or not
 * Added to Travis CI

JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by jiangzidong** [comment]
in ecma-typedarray-object.c, it is `addtogroup ecmatypedarrayobject ECMA %TypedArray% object related routines`
however in ecma-typedarray-object.h, the sentence is different `addtogroup ecmatypedarrayobject ECMA typedarray object related routines`

It should be same, and It is my mistake. I've fixed it in #1532

**Comment by LaszloLango** [comment]
@jiangzidong I can wait for #1532. I should finish the review of it at first, but it's too big. :)

**Comment by jiangzidong** [comment]
That's fine:) Maybe you should also modify the `ecma-typedarray-object.h` in your patch. 

And I will try to separate the big patch into small ones next time.

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
