### PR TITLE
Calculate length of the array inside function instead of add as a parameter

### PR DESCRIPTION
**Pull request by robertsipka**

### CODE REVIEW

**Comment by LaszloLango** [comment]
Please wait for Travis CI, before merge.

**Comment by zherczeg** [comment]
It seems it broke some tests:

=== Summary ===
 - Ran 11552 tests
 - Passed 11540 tests (99.9%)
 - Failed 12 tests (0.1%)

Failed tests
  ch07/7.6/S7.6_A4.2_T1 in non-strict mode
  ch07/7.6/S7.6_A4.2_T2 in non-strict mode
  ch09/9.3/9.3.1/S9.3.1_A2 in non-strict mode
  ch09/9.3/9.3.1/S9.3.1_A3_T1 in non-strict mode
  ch09/9.3/9.3.1/S9.3.1_A3_T2 in non-strict mode
  ch15/15.1/15.1.2/15.1.2.2/S15.1.2.2_A2_T10 in non-strict mode
  ch15/15.1/15.1.2/15.1.2.3/S15.1.2.3_A2_T10 in non-strict mode
  ch15/15.5/15.5.4/15.5.4.20/15.5.4.20-3-2 in non-strict mode
  ch15/15.5/15.5.4/15.5.4.20/15.5.4.20-3-3 in non-strict mode
  ch15/15.5/15.5.4/15.5.4.20/15.5.4.20-3-4 in non-strict mode
  ch15/15.5/15.5.4/15.5.4.20/15.5.4.20-3-5 in non-strict mode
  ch15/15.5/15.5.4/15.5.4.20/15.5.4.20-3-6 in non-strict mode

Btw the mac bots seem hanging for all PRs, do you know the reason for that?

**Comment by LaszloLango** [comment]
There were some issues with them, but they should work from now. Check Travis status for details: https://www.traviscistatus.com/

**Comment by robertsipka** [comment]
It's my bad, I looked over that the compiler doesn't know what the pointer is pointing to, so in this case it doesn't return with the number of elements. I'am closing it now.

**Pull request closed without merging**
