### PR TITLE
targets: zephyr: Update for Zephyr 1.13

### PR DESCRIPTION
**Pull request by pfalcon**
Zephyr 1.13 made some refactorings to its CMake infrastructure which must
be propagated to applications.

Also, some config options were removed/refactored, so cleanup prj.conf.

JerryScript-DCO-1.0-Signed-off-by: Paul Sokolovsky paul.sokolovsky@linaro.org

### CODE REVIEW

**Comment by akosthekiss** [comment]
@pfalcon The CI's Zephyr build job is failing after this update

**Comment by pfalcon** [comment]
@akosthekiss: Yeah:

~~~
Installing SDK to /home/travis/build/jerryscript-project/zephyr-sdk-0.9.2
git clone https://github.com/zephyrproject-rtos/zephyr.git ../zephyr -b v1.10.0
~~~

So, it uses pretty old Zephyr release and previous version of SDK. Let me update Travis-related infra with this PR too. Zephyr 1.13 itself is in RC phase now, with the release in a week or so. Until all that is done, let me mark this as WIP.

**Comment by pfalcon** [comment]
As an update, this now builds against  v1.13.0-rc3 and passes CI. The release should be tagged next week.

**Comment by pfalcon** [comment]
@zherczeg, @akosthekiss: Zephyr 1.13 was released, this PR was updated to build with the release tag and passes CI. Should be ready to merge.

**Comment by pfalcon** [comment]
> oh wait, no, sorry. please, squash the commits

You have strange rules, guys. First commit is for *code* changes, 2nd - for *CI infrastructure*, what's sense to squash them? But done.

**Comment by akosthekiss** [comment]
@pfalcon That's one way to look at it. From my perspective, all this is a build system bump. And also the project custom is one commit per PR -- if changes are independent enough to be broken into separate commits then separate PRs should also be opened. And each PR/commit shall pass on the CI on its own. I'm not sure this would've worked here. Anyway, the important thing is that the update has landed in master.

**Comment by pfalcon** [comment]
@akosthekiss:

Thanks for response, indeed, such schedule also has its place.

> Anyway, the important thing is that the update has landed in master.

Indeed, thanks!

**Pull request merged**
