### PR TITLE
[WIP] Add build option to generate jerryscript-snapshot-compiler.js

### PR DESCRIPTION
**Pull request by martijnthe**
This adds a way to generate a JavaScript library / module
"jerryscript-snapshot-compiler.js" that can take a JS source string and produce
a JerryScript snapshot. This library is produced using the Emscripten compiler,
transpiling the C code that produces snapshots into JS. The advantage of such
a library as opposed to the binary "jerry" program is that as-is (without having
to recompile anything), it can be run on other platforms (i.e. cloud, mobile,
browser, etc.).

Use `tools/build.py --emscripten-snapshot-compiler ON` to generate the output.
Note that you need to have the Emscripten SDK activated.
Hint: run `source $PATH_TO_EMSDK/emsdk_env.sh` first.

JerryScript-DCO-1.0-Signed-off-by: Martijn The martijn.the@intel.com

# TODOs:

- [ ] Extend `run-tests.py` + `.travis.html` to build `jerryscript-snapshot-compiler.js` and produce snapshots for all the .js test files, then execute them using a binary JerryScript "engine" (not a transpiled one).

### CODE REVIEW

**Comment by martijnthe** [comment]
As per my own issue:
https://github.com/jerryscript-project/jerryscript/issues/1977

**Comment by slaff** [comment]
@martijnthe Is the generated snapshot compatible with the latest latest JerryScript version?  Will it be possible to run the JS snapshot creator in a modern browser without the need to connect to external service?

**Comment by martijnthe** [comment]
@slaff :

My hope with this effort was to create a "universal" JrS compiler. "Unfortunately", JerryScript has a number of build-time configuration parameters that affect the snapshot output. So those would have to match with the engine you are targeting too.

I guess it's in theory possible to transpile the JerryScript snapshot generation code for all the various configuration combinations and bundle the variants up into a single "universal" compiler. But that's a bit more work than I'm willing to invest in this at this moment... Feel free to take this branch and add it :) You can take a look at `jerry_snapshot_header_t` to see what the configuration variables are that affect the snapshot output.

> Is the generated snapshot compatible with the latest JerryScript version?

The PR has fallen behind. If you merge master into this branch it will be compatible with latest JrS again. The JrS C sources are used to create the snapshot creator after all...

> Will it be possible to run the JS snapshot creator in a modern browser without the need to connect to external service?

Yes.

**Comment by slaff** [comment]
> I guess it's in theory possible to transpile the JerryScript snapshot generation code for all the various configuration combinations and bundle the variants up into a single "universal" compiler. But that's a bit more work than I'm willing to invest in this at this moment..

@martijnthe Ok, understood. I am trying to compile the code but I got one compilation issue:

```
$ source $EMSDK/emsdk_env.sh && python tools/build.py --emscripten-snapshot-compiler ON
...
[ 99%] Building C object emscripten-snapshot-compiler/CMakeFiles/jerryscript-snapshot-compiler.dir/emscripten-snapshot-compiler.c.o
/home/slavey/dev/jerryscript/emscripten-snapshot-compiler/emscripten-snapshot-compiler.c:17:24: fatal error: emscripten.h: No such file or directory
 #include <emscripten.h>
                        ^
compilation terminated.
```

I added the following options
```
source $EMSDK/emsdk_env.sh && python tools/build.py --emscripten-snapshot-compiler ON --verbose --compile-flag="-I$EMSCRIPTEN/system/include" --snapshot-exec ON --snapshot-save ON
```

But then ended up with much more compilation errors. Can you, please, give me hints what am I doing wrong?

**Comment by martijnthe** [comment]
@slaff what Emscripten version are you using (`emsdk list` will show you which is active)? And what OS platform are you on? I've been using `sdk-1.37.9-64bit` on macOS and also Ubuntu 16.04.

**Comment by slaff** [comment]
> what Emscripten version are you using 

@martijnthe Here is the information that I've got:

```
emsdk list 

The following precompiled tool packages are available for download:
           clang-nightly-e1.37.9-2017_03_30_17_42-64bit
           clang-nightly-e1.37.9-2017_03_30_19_17-64bit
           clang-e1.37.1-64bit      
           clang-e1.37.21-64bit     
     *     clang-e1.37.22-64bit     	INSTALLED
           node-4.1.1-32bit         
     *     node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        
           emscripten-1.37.1        
           emscripten-1.37.21       
     *     emscripten-1.37.22       	INSTALLED
           emscripten-nightly-1.37.9-2017_03_30_17_42
           emscripten-nightly-1.37.9-2017_03_30_19_17

The following tools can be compiled from source:
           clang-tag-e1.37.21-32bit 
           clang-tag-e1.37.22-32bit 
           clang-tag-e1.37.21-64bit 
           clang-tag-e1.37.22-64bit 
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
           clang-master-64bit       
           emscripten-tag-1.37.21-32bit
           emscripten-tag-1.37.22-32bit
           emscripten-tag-1.37.21-64bit
           emscripten-tag-1.37.22-64bit
           binaryen-tag-1.37.21-32bit
           binaryen-tag-1.37.22-32bit
           binaryen-tag-1.37.21-64bit
           binaryen-tag-1.37.22-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
           emscripten-master-64bit  
           binaryen-master-32bit    
           binaryen-master-64bit    

The following precompiled SDKs are available for download: (Run "./emsdk update" to pull in the latest list)
         sdk-nightly-1.37.9-2017_03_30_17_42-64bit
         sdk-nightly-1.37.9-2017_03_30_19_17-64bit
         sdk-1.37.21-64bit        
    *    sdk-1.37.22-64bit        	INSTALLED

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
         sdk-master-64bit         
         sdk-tag-1.37.21-32bit    
         sdk-tag-1.37.22-32bit    
         sdk-tag-1.37.21-64bit    
         sdk-tag-1.37.22-64bit    

Items marked with * are activated for the current user.

To access the historical archived versions, type 'emsdk list --old'
```

OS: Ubuntu 14.04 LTS, gcc 4.8.

**Comment by martijnthe** [comment]
> OS: Ubuntu 14.04 LTS

I've had trouble getting emsdk to work on 14.04 in the past.
I'd try upgrading to 16.04.

**Comment by martijnthe** [comment]
@slaff jfyi, as part of #1901, we're using a Dockerfile to run Emscripten on Ubuntu 16.04:

https://github.com/jerryscript-project/jerryscript/pull/1901/files#diff-0ad690576a7fe41e5c6a575116c68985

Perhaps that's an easier way to try it out rather than upgrading your system to 16.04.

**Pull request closed without merging**
