### PR TITLE
WIP tentative fixes the CI.

### PR DESCRIPTION
**Pull request by lygstate**
This is a combine of multiple patches.
1. Fixes timeout error on windows. , timeout are not working on windows.
2. Upgrade all to ubuntu 20.04
3. Switch to python3

### CODE REVIEW

**Comment by akosthekiss** [comment]
@lygstate Please, don't do this.

- This PR is still opened from your master branch. Please use git branches for development.
- This PR still has multiple commits (7 at the moment).
- The commit messages are still a mix. Non-English is not understood by most of the maintainers.
- Please don't use PRs for _testing_ your solutions. First of all, test your changes locally on your development machine. Then, have a fork of the repo on GH, have a branch therein for your changes, and push versions of your commit only there. _Your_ Travis CI account and _your_ GH Actions should be used to test them. Once everything is green, only then open a PR from the branch.

I'll keep closing PRs like this one when I see that they are used incorrectly.

**Comment by akosthekiss** [comment]
Other than that, have separate PRs for separate enhancement ideas.
- Bumping Ubuntu version is one thing.
- Fixing Windows timeout is another.
- Switching to python3 is yet another.

Maintainers may accept some of those ideas while reject others. (E.g., Ubuntu version bump is questionable without any justification given. It works now, who needs the change any why? Dropping Python2 support is again something some people may strongly argue against. Right now, our scripts work on all Python versions. What makes it necessary to drop the support of Python2? Does it block any functionality that mandates that change?)

**Comment by lygstate** [comment]
@akosthekiss Please don't close this, I am using this to trigger the CI. after things fine, I'll split them

**Comment by akosthekiss** [comment]
But you _do_ know that you can trigger your own CI, don't you?

**Comment by lygstate** [comment]
> But you _do_ know that you can trigger your own CI, don't you?

It's triggered now, but 3 hours ago, it's doesn't triggered.

**Pull request closed without merging**
