### PR TITLE
target: mbedos5: use jerry-ext

### PR DESCRIPTION
**Pull request by fbmrk**
Update target mbedos5 to use external function handlers: `assert`, `gc` and `print` from jerry-ext.
See #1857 

JerryScript-DCO-1.0-Signed-off-by: Marko Fabo mfabo@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
@janjongboom please check

**Comment by akosthekiss** [comment]
Beware that the PR changes the behaviour of JS `assert`! Existing implementation throws a JS error, but jerry-ext implementation kills the engine.

**Comment by janjongboom** [comment]
@akosthekiss I don't think people rely on `assert` in that way. Other than that LGTM.

**Comment by akosthekiss** [comment]
@janjongboom thanks for reviewing the PR. I have nothing against the change, just didn't want it to go unnoticed.

**Pull request merged**
