### PR TITLE
Combine ARRAYBUFFER and TYPEDARRAY macros together

### PR DESCRIPTION
**Pull request by jiangzidong**
updated according to the 2nd idea of https://github.com/jerryscript-project/jerryscript/pull/1699#issuecomment-290325703

Since arraybuffer and typedarray will not exist separately, I plan to change ~~`CONFIG_DISABLE_ES2015_TYPEDARRAY_BUILTIN` to `CONFIG_DISABLE_ES2015_ARRAYBUFFER_BUILTIN`.~~
`CONFIG_DISABLE_ES2015_ARRAYBUFFER_BUILTIN` to `CONFIG_DISABLE_ES2015_TYPEDARRAY_BUILTIN`

~~In this way, `ArrayBuffer`, `TypedArray` and future `DataView` should be under the same macro, and be disabled/enabled simultaneously.~~

### CODE REVIEW

**Comment by zherczeg** [comment]
Just a question: why do we choose arraybuffer instead of typed array which is a more popular name. I think many people are not aware that typed arrays are backed by array buffers.

**Comment by jiangzidong** [comment]
Because both typedarray and dataview will use arraybuffer, so I plan to put those 3 features under arraybuffer macro.

But another solution is:
Now we use typedarray macro to enable both typedarray and arraybuffer
Later (when we implement dataview), we use dataview macro to enable dataview, and use `dataview_macro | typedarray_macro` to enable arraybuffer.
In this way, typedarray and dataview can be enabled separatedly.

**Comment by zherczeg** [comment]
I wouldn't mind to have a single macro for the whole feature set. Anyway I like your second idea. There is no point to have arraybuffer only.

**Comment by jiangzidong** [comment]
@zherczeg @LaszloLango updated.

**Comment by LaszloLango** [comment]
still LGTM

**Pull request merged**
