### PR TITLE
Master fork

### PR DESCRIPTION
**Pull request by lygstate**
**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

Before submitting a PR, please, make sure that:

- Changes are in a separate branch, not in master.
- The branch contains only one commit on top of master (if not, squash them into
  one commit).
- The commit has a descriptive commit message with a concise title (first line).
- The commit message contains `fixes #XXXX` or `closes #XXXX` to auto-close the
  issue(s) that the PR fixes (if any).
- Tests for the changes have been added (for bug fixes / features).
- Documentation has been added / updated (if applicable).
- All new and existing tests passed locally (if not, fix them first and amend
  the commit).

IMPORTANT: Please review the CONTRIBUTING.md file for detailed contributing
guidelines.

**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

### CODE REVIEW

**Comment by akosthekiss** [comment]
@lygstate Please, explain what you are doing. You cannot open a PR by mistake. You cannot open PRs by mistake TWICE.

**Comment by lygstate** [comment]
> @lygstate Please, explain what you are doing. You cannot open a PR by mistake. You cannot open PRs by mistake TWICE.

It's a mistake and also by github, I am trying to PR to my own jerryscript repo to trigger the CI, but it's default to jerryscript not to my own and this is the result

**Comment by akosthekiss** [comment]
@lygstate Now that #4395 has landed, it should be easier to trigger the CI. Any branch you push to your fork will trigger GH Actions on your fork, even without a PR.

**Comment by lygstate** [comment]
@akosthekiss thanks.

**Pull request closed without merging**
